### ISSUE TITLE
Support for single ports

### ISSUE THREAD

**Issue by thehunmonkgroup** [yassen-itlabs/py-linux-traffic-control#2]
Currently trying to use a single port fails:

```
root@webrtc-test-0.stirlab.net$/var/local/git/py-linux-traffic-control: pyltc tc --iface eth0 -v --dclass tcp:443:512kbit
Namespace(clear=False, dclass=['tcp:443:512kbit'], iface='eth0', ingress=None, sclass=None, subparser='tc', verbose=True, version=False)
Traceback (most recent call last):
File "/usr/local/bin/pyltc", line 1299, in <module>
main(sys.argv[1:])
File "/usr/local/bin/pyltc", line 883, in main
build_tree(chain, tcp_hook, udp_hook, args.dclass, offset=2, is_ingress=bool(args.ingress))
File "/usr/local/bin/pyltc", line 698, in build_tree
start, end = (int(elm) for elm in branch['range'].split("-"))
```

**Comment by yassen-itlabs** [comment]
Resolved with dee9dbdad8785ec2aa26a58bd4370c605cb73be3. Closing.
