### ISSUE TITLE
Crash when using profiles without -v arg

### ISSUE THREAD

**Issue by thehunmonkgroup** [yassen-itlabs/py-linux-traffic-control#8]
See below:

```
root@webrtc-test-0.stirlab.net$/var/local/git: cat /etc/pyltc.profiles 
[4g-sym]
clear
iface eth0
dclass tcp:443:512kbit
dclass tcp:8080:512kbit
dclass tcp:8082:512kbit
dclass udp:10000-35000:512kbit

root@webrtc-test-0.stirlab.net$/var/local/git: pyltc profile 4g-sym
Traceback (most recent call last):
  File "/usr/local/bin/pyltc", line 20, in <module>
    sys.exit(pyltc_entry_point())
  File "/var/local/git/py-linux-traffic-control/pyltc/main.py", line 36, in pyltc_entry_point
    args = parse_args(argv)
  File "/var/local/git/py-linux-traffic-control/pyltc/parseargs.py", line 142, in parse_args
    args.verbose = args.verbose or old_args_dict['verbose']
KeyError: 'verbose'
```

If I provide the -v arg specifically, the command succeeds.

**Comment by yassen-itlabs** [comment]
Fixed with d4dfac4ed67d8aac0f262d83407e398dd8fef92a, closing.
